---
- name: Add download tasks
  include_tasks: download/{{ ansible_pkg_mgr }}.yml

- name: Add install tasks
  include_tasks: install/{{ ansible_pkg_mgr }}.yml

- name: Add configure tasks
  include_tasks: configure.yml
