---
dependency:
  name: galaxy
  enabled: false
driver:
  name: podman
platforms:
  - name: centos7
    image: docker.io/pycontribs/centos:7
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
  #- dependency                                                                                                                                                        
  #- lint                                                                                                                                                              
  #- cleanup                                                                                                                                                           
  - destroy                                                                                                                                                           
  - syntax                                                                                                                                                            
  - create                                                                                                                                                            
  #- prepare                                                                                                                                                           
  - converge                                                                                                                                                          
  - idempotence                                                                                                                                                       
  #- side_effect                                                                                                                                                       
  #- verify                                                                                                                                                            
  #- cleanup                                                                                                                                                           
  - destroy                                                                                                                                                           
 