---
- name: Get vector distrib rpm
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
    dest: vector.rpm
    mode: 0755
  check_mode: false
  register: result
  timeout: 60
  until: result is succeeded
  retries: 10
